# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Pull Request Checker

on:
  pull_request:
    branches:
      - '**'
      - '!mainline'

permissions:
  contents: read

jobs:
  test:

    runs-on:
      labels: kernel-build
    strategy:
      matrix:
        ruby-version: ['3.0']

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Checkout base branch
      run: |
        git remote add base_repo https://github.com/${{ github.repository }}.git
        git fetch base_repo ${{ github.base_ref }}:${{ github.base_ref }}

    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
    # uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Run tests
      run: |
        /usr/bin/pip3 install gitPython
        python -c "import sys; import git; print(sys.version)"
        git remote add linux https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
        git fetch --shallow-since="3 years ago" linux
        echo "Will run process-git-request.rb with:"
        echo "fname = ${{ github.run_id }}"
        echo "target_branch = ${{ github.base_ref }}"
        echo "source_branch = ${{ github.head_ref }}"
        echo "prj_dir = ${{ github.workspace }}"
        echo "pull_request = ${{ github.ref }}"
        echo "requestor = ${{ github.actor }}"
        cd ${{ github.workspace }}
        /usr/bin/ruby .github/workflows/process-git-request.rb ${{ github.run_id }} ${{ github.base_ref }} \
        ${{ github.head_ref }} ${{ github.workspace }} ${{ github.ref }} ${{ github.actor }} 
